# Generated by Django 3.1.5 on 2021-01-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210109_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
